from PIL import Image, ImageDraw, ImageFont

# Read system information from the text file generated by the shell script
with open("/tmp/crossmix_info/app_cpu_info.txt", "r") as f:
    text = f.read()

# Open the background image
img = Image.open("input_image.png")
draw = ImageDraw.Draw(img)

# Load the font
font = ImageFont.truetype("/mnt/SDCARD/Themes/CrossMix - OS/wqy-microhei.ttf", 18)
# font = ImageFont.load_default()

# Draw the text onto the image
draw.text((25, 25), text, font=font, fill=(255, 255, 255))  # white

# Save the resulting image
img.save("/tmp/crossmix_cpu_info/app_cpu_info.png")
