#!/bin/sh
C=''
for i in "$@"; do
    case "$i" in
        -O*)
           i="-o"
    C="$C $i"
	;;
        -*)
          echo raw
    C="$C $i"
	;;
        *\'*)
            i=`printf "%s" "$i" | sed "s/'/'\"'\"'/g"`
            ;;
        *) : ;;
    esac
    if [[ ${i:0:1} == "-" ]] ; then
       echo raw2
    else
      C="$C '$i'"
    fi
done

echo curl -L --connect-timeout 30 --max-time 120 -k "$C" >/tmp/c.sh
sed -i $'s/\'/\"/g' /tmp/c.sh
cat /tmp/c.sh
chmod +x /tmp/c.sh
/tmp/c.sh
